### ISSUE TITLE
Bottom buttons are misplaced

### ISSUE THREAD

**Issue by alextanasie** [alexVee90/TwtrClone#2]
Too much left spacing, not aligned with top content

![Screenshot 2020-03-04 at 10 52 40](https://user-images.githubusercontent.com/18068016/75861775-860c7700-5e06-11ea-8955-d1dea8bb2ae7.png)

**Comment by alexVee90** [comment]
fixed 

![image](https://user-images.githubusercontent.com/53277163/76078022-7e85d300-5faa-11ea-8d66-379ddc01d0fb.png)

code: 

![image](https://user-images.githubusercontent.com/53277163/76078068-96f5ed80-5faa-11ea-8263-524788bdd6c5.png)
