### ISSUE TITLE
<li> for non-lists

### ISSUE THREAD

**Issue by alextanasie** [alexVee90/TwtrClone#3]
https://github.com/alexVee90/TwtrClone/blob/0f4628f6014c44381c2ddc2dc841f2b4f79de822/index.html#L165

Since the semantic here is not really about a list (a tweet is rather a piece of the main content on the page), another element should have been used in this case.

**Comment by alexVee90** [comment]
changed the structure as so: 

![image](https://user-images.githubusercontent.com/53277163/76079424-4c29a500-5fad-11ea-8237-0258f163a632.png)

adjusted the css to use the new class names: 

![image](https://user-images.githubusercontent.com/53277163/76079494-6a8fa080-5fad-11ea-86d3-a064059d7437.png)
