### ISSUE TITLE
Missing styles for hover states

### ISSUE THREAD

**Issue by alextanasie** [alexVee90/TwtrClone#4]
There are no hover effects for buttons (except login/signup) & links.

**Comment by alexVee90** [comment]
hover effect is also added for the follow buttons, also for the meatballs menu: 

![image](https://user-images.githubusercontent.com/53277163/76080219-1a194280-5faf-11ea-8c09-6d83539c88a8.png)

just added effects for the links as well

![image](https://user-images.githubusercontent.com/53277163/76080856-86e10c80-5fb0-11ea-8be7-4bcf23cad63a.png)

![image](https://user-images.githubusercontent.com/53277163/76080905-a5df9e80-5fb0-11ea-9381-965e2dba7a61.png)

![image](https://user-images.githubusercontent.com/53277163/76081006-d9222d80-5fb0-11ea-8827-cfa94ddbb713.png)
